defaultIndent: '  '

indentRulesGlobal:
  environments: "  "
  optionalArguments: ""
  mandatoryArguments: "  "
  commands: ""
  UnNamedGroupingBracesBrackets: ""
  afterHeading: ""

indentRules:
  longtable: ""

lookForAlignDelims:
  tabular: 0
  longtable: 0

commandCodeBlocks:
  stringsAllowedBetweenArguments:
    - amalgamate: 0
    - '\\x\/\\y in'
    - '\\i in'

specialBeginEnd:
  addwireframetcbset:
    begin: '\#1frame\/\.style\=\{'
    end: '\}'
