defaultIndent: '  '

indentRulesGlobal:
  environments: "  "
  optionalArguments: ""
  mandatoryArguments: "  "
  commands: ""
  UnNamedGroupingBracesBrackets: ""
  afterHeading: ""

noAdditionalIndent:
  foreach: 1

commandCodeBlocks:
  stringsAllowedBetweenArguments:
    - amalgamate: 0
    - '\\x\/\\y in'
    - '\\i in'
