defaultIndent: '  '

indentRulesGlobal:
  environments: "  "
  optionalArguments: ""
  mandatoryArguments: "  "
  commands: ""
  UnNamedGroupingBracesBrackets: ""
  afterHeading: ""

indentRules:
  longtable: ""
  problem: "  "

lookForAlignDelims:
  tabular: 0
  longtable: 0
  array: 0
  align: 0
  align*: 0

commandCodeBlocks:
  stringsAllowedBetweenArguments:
    - amalgamate: 0
    - '\\x\/\\y in'
    - '\\x in'
    - '\\i in'

specialBeginEnd:
  addwireframetcbset:
    begin: '\#1frame\/\.style\=\{'
    end: '\}'
