defaultIndent: '  '

replacements:
  - 
    substitution: s/^(.*?)%\h*noindent/%\\begin\{noindent\}$1%\\end\{noindent\}/mg
    when: before
  - 
    substitution: s/%\\begin\{noindent\}(.*?)%\\end\{noindent\}/$1% noindent/mg
    when: after

specialBeginEnd:
  tikzDraw:
    begin: \\draw(?![A-Za-z])
    end: ';'
  tikzPath:
    begin: '\\path'
    end: ';'
  tikzForEach:
    begin: \\foreach\s+\\(?:[a-zA-Z@]+)(?:/\\(?:[a-zA-Z@]+))?\s+in\s+\{
    middle: \}\s+\{
    end: \}
  literate:
    begin: 'literate=%'
    end: ','
  specialBeforeCommand: 1

indentRulesGlobal:
  environments: "  "
  optionalArguments: "  "
  mandatoryArguments: "  "
  commands: "  "
  UnNamedGroupingBracesBrackets: ""
  afterHeading: ""

indentRules:
  longtable: ""
  lstdefinestyle:
    mandatoryArguments: "  "
  tikzDraw: "  "
  tikzPath: "  "
  tikzForEach:
    body: "  "
  literate:
    body: "  "
  caption:
    body: ""
    mandatoryArguments: "  "
  NewDocumentCommand:
    body: "  "
    mandatoryArguments: "  "

noAdditionalIndentGlobal:
  keyEqualsValuesBracesBrackets: 1
  optionalArguments: 1

noAdditionalIndent:
  problem: 0
  caption: 0
  tikzForEach: 0
  NewDocumentCommand:
    body: 0
    mandatoryArguments: 0

lookForAlignDelims:
  tabular:
    multiColumnGrouping: 1
    dontMeasure:
      - abcefg
      - cf
      - bdf
      - ef
      - abcdfg
      - ce
      - abeg
      -
        regex: '\\multicolumn\{1\}\{\|c\}\{[01]\}'
    alignDoubleBackSlash: 0
  longtable:
    dontMeasure: 1
    alignDoubleBackSlash: 0
  split:
    alignDoubleBackSlash: 0
