defaultIndent: '  '

indentRulesGlobal:
  environments: "  "
  optionalArguments: ""
  mandatoryArguments: "  "
  commands: ""
  UnNamedGroupingBracesBrackets: ""
  afterHeading: ""

noAdditionalIndent:
  foreach: 1
