defaultIndent: '  '

specialBeginEnd:
  tikzPath:
    begin: '\\path'
    end: ';'
  specialBeforeCommand: 1

indentRulesGlobal:
  environments: "  "
  optionalArguments: "  "
  mandatoryArguments: "  "
  commands: ""
  UnNamedGroupingBracesBrackets: ""
  afterHeading: ""

indentRules:
  longtable: ""

noAdditionalIndentGlobal:
  keyEqualsValuesBracesBrackets: 1

noAdditionalIndent:
  problem: 0

lookForAlignDelims:
  tabular:
    dontMeasure: 1
  longtable:
    dontMeasure: 1
  tikzPath:
    delimiterRegEx: ’(edge|node)’
  split:
    alignDoubleBackSlash: 0

commandCodeBlocks:
  stringsAllowedBetweenArguments:
    - amalgamate: 0
    - '\\x\/\\y in'
    - '\\x in'
    - '\\y in'
    - '\\i in'
