defaultIndent: '  '

indentRulesGlobal:
  environments: "  "
  optionalArguments: "  "
  mandatoryArguments: "  "
  commands: ""
  UnNamedGroupingBracesBrackets: ""
  afterHeading: ""

indentRules:
  longtable: ""

noAdditionalIndent:
  problem: 0

lookForAlignDelims:
  tabular: 0
  longtable: 0
  tikzPath:
    delimiterRegEx: ’(edge|node)’

commandCodeBlocks:
  stringsAllowedBetweenArguments:
    - amalgamate: 0
    - '\\x\/\\y in'
    - '\\x in'
    - '\\y in'
    - '\\i in'

specialBeginEnd:
  tikzPath:
    begin: '\\path'
    end: ';'
  specialBeforeCommand: 1
